### ISSUE TITLE
Feature: User can create mood board and add to db

### ISSUE THREAD

**Issue by lisale841** [lisale841/final-project-template-#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

- User has the capability to add a blank mood board to db

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes
![Screen Shot 2022-02-20 at 6 34 13 PM](https://user-images.githubusercontent.com/93673754/154879871-5de695a4-4ef2-453d-b26c-68359ccc1dea.png)
![Screen Shot 2022-02-20 at 6 34 27 PM](https://user-images.githubusercontent.com/93673754/154879874-09087964-8ebf-4043-9cac-81e450548547.png)
![Screen Shot 2022-02-20 at 6 34 55 PM](https://user-images.githubusercontent.com/93673754/154879876-3b9a47c8-8c9e-4fbd-b672-1db945ea444a.png)
![Screen Shot 2022-02-20 at 6 35 01 PM](https://user-images.githubusercontent.com/93673754/154879878-f02ccf7a-e87e-45cf-9806-20f5bb019cda.png)

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` with the db designer final project schema approved by Tim.
- [x] Update `data.sql` to make userId 1 as admin for now. 

### ☁️ Server

- [x] add all required packages.
- [x] update server/index.js to respond to user sign-in which is (admin for now) -
 -create index.js in the server directory that responds to user sign-in. Post request. that requires client to have username and password in the request. SQL and Params.  Query the database to look for the user verify if hashed pw and password matches.  Then token.
- [x] create client-error js file
- [x] create error-middleware file
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to let user navigate to the create mood board 
- [x] Create the navigation bar
- [x] Create the components for the mood board for user : just the css for now functionalities will be added in following task list items

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
