### ISSUE TITLE
Feature: User can visualize moodboard. 

### ISSUE THREAD

**Issue by lisale841** [lisale841/final-project-template-#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can visualize the mood board created.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

So far the user can see the webpage's home screen, see the about page, click on create a mood board which creates a new mood board Id into the db.  However, they cannot visualize the mood board that they have created.  In this next feature the plan is to allow the user to see the "blank mood board that was created in the view my mood board page"  Also in this feature I will be creating the mood board canvas space and having it mobile responsive.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="305" alt="Screen Shot 2022-02-22 at 12 40 32 PM" src="https://user-images.githubusercontent.com/93673754/155215910-b4f6081b-8bf1-4ded-ad25-5d9935217ab5.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to pull up the created mood board to show in the "my mood board section"
- [x] Handle all errors and respond to the client
- [x] check with HTTPie

### ⚡ Client

- [x] Create components to show the mood board created 
- [x] create component to direct user to the "my mood boards" 
- [x] create components to allow mobile user to see the mood board easily on mobile.

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

![Screen Shot 2022-02-23 at 12 26 22 AM](https://user-images.githubusercontent.com/93673754/155284037-85ee8f67-62fa-4aa2-bbc0-aeda40ddbdfd.png)
