### ISSUE TITLE
Feature: User can add photos onto  the mood board 

### ISSUE THREAD

**Issue by lisale841** [lisale841/final-project-template-#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can add photos/ text onto the mood board.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
Up until now user can log into the webpage and view the about me page.  Clicking on the hamburger menu they can click on My mood boards to be directed to the list of mood boards.  On that page they can click on the plus sign to create a new mood board.  After creating a new mood board they will be directed to the edit mood board page.  However up until now the user has no capability to do anything to the blank mood board.  For this feature the user can upload photos onto the mood board.

## 🖼️ Wireframes
<img width="192" alt="Screen Shot 2022-02-23 at 10 49 39 AM" src="https://user-images.githubusercontent.com/93673754/155387467-06498d81-5a15-4673-8c42-b39a4a55802b.png">
<img width="368" alt="Screen Shot 2022-02-23 at 10 57 43 AM" src="https://user-images.githubusercontent.com/93673754/155388551-bb6ae684-dcfa-451e-bb89-071c4df9d3df.png">

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update server/index.js so that the moodBoardObj table updates when the user uploads an image. 
    - review file upload exercise "URL" get/post req
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update current component to allow user to upload photos : "fetch"

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
