### ISSUE TITLE
Feature: User can save the mood board 

### ISSUE THREAD

**Issue by lisale841** [lisale841/final-project-template-#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save the edited mood board. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Up until now the user can add photos onto the mood board as well as resizing and dragging the images on the mood board.  However, location of the mood board object is not saved upon drag.  For this feature the user can save the mood board and if they moved the object it will save the coordinates on the database . 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screen Shot 2022-02-24 at 2 48 48 PM](https://user-images.githubusercontent.com/93673754/155621421-3fdf7d39-6dfc-4c13-aad7-feb17a1e1e3d.png)
![Screen Shot 2022-02-24 at 2 51 54 PM](https://user-images.githubusercontent.com/93673754/155621543-00d263e5-96de-422c-965a-7ec3cdb5b615.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to show the updated coordinates for the mood object.
-  app.put('/api/mood-objects/:moodObjectId', (req, res, next) => {
})
  
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to save the mood board after user does all edits.
- need to review the interact.js ".draggable has an event listener that keeps track of the data-x and data-y coordinates. 👍 

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
